version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    tty: true
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "15672:15672"
      - "5672:5672"

  mysql:
    image: mysql:8.0
    container_name: pos_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pos_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./core_services/databases/migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  rabbitmq_data:
    driver: local
  mysql_data:
    driver: local